build(ci): load qemu-user-static in docker

diff --git a/.github/workflows/build-and-deploy-nvme-tcp.yml b/.github/workflows/build-and-deploy-nvme-tcp.yml
--- a/.github/workflows/build-and-deploy-nvme-tcp.yml
+++ b/.github/workflows/build-and-deploy-nvme-tcp.yml
@@ -32,22 +32,28 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
+      - name: install qemu for cross-compilation
+        if: matrix.board_arch == 'arm64'
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y qemu-user-static
+          cat /proc/sys/fs/binfmt_misc/qemu-aarch64 || true
+          cat /usr/lib/binfmt.d/qemu-aarch64-static.conf || true
+          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
+          if ! [ -x /usr/bin/qemu-aarch64-static ]; then
+            echo "Error: /usr/bin/qemu-aarch64-static not found. Please install qemu-user-static on your host."
+            exit 1
+          fi
+          if ! grep -q enabled /proc/sys/fs/binfmt_misc/qemu-aarch64; then
+            echo "Error: qemu-aarch64 binfmt_misc entry not enabled. Please register qemu-aarch64-static with binfmt_misc."
+            exit 1
+          fi
+
       - name: Run docker-nvme-tcp.sh
         #if: github.ref == 'refs/heads/main'
         run: |
           if [ "${{ matrix.board_arch }}" = "arm64" ]; then
             echo "Building for ARM64 architecture"
-            echo "Installing qemu-user-static for ARM64 cross-compilation"
-            sudo apt-get update
-            sudo apt-get install -y qemu-user-static
-            if ! [ -x /usr/bin/qemu-aarch64-static ]; then
-              echo "Error: /usr/bin/qemu-aarch64-static not found. Please install qemu-user-static on your host."
-              exit 1
-            fi
-            if ! grep -q enabled /proc/sys/fs/binfmt_misc/qemu-aarch64; then
-              echo "Error: qemu-aarch64 binfmt_misc entry not enabled. Please register qemu-aarch64-static with binfmt_misc."
-              exit 1
-            fi
           else
             echo "Building for AMD64 architecture"
           fi
